### ISSUE TITLE
Connect to no-existing server

### ISSUE THREAD

**Issue by thijstriemstra** [hwmrocker/smtplibaio#8] opened 2016-11-28 15:29 UTC
I'd like to use this package on a raspberry pi with a bad internet connection, meaning it might not find the STMP server at all times. When you connect to a non-existing server, e.g. `foo` on port 10234, the call to `sendmail` will hang forever and never times out. How do I detect this, is there a timeout I can specify?

**Comment by Frzk** [comment] 2016-11-28 16:09
Normally, if the server can't be reached, the `connect` method (which is called when entering the asynchronous context manager) should raise an Exception. So you shouldn't even be able to call `sendmail` in this case.

I'll try to investigate this ASAP and see if I can submit a fix.

Regarding timeout support, currently, the Streams API we are using doesn't support it. See https://bugs.python.org/issue23236. That's obviously something we will add as soon as it lands in the API.

**Comment by Frzk** [comment] 2016-11-28 16:59
I can't reproduce what you are experiencing. When I try to connect to a non-existing server, I get Exceptions (`socket.gaierror` or `OSError`) after a while. These exceptions aren't mentioned in the `connect` and `__aenter__` docstrings. That's something I'll fix.

Can you please provide some more details / code ?

Also, what makes you think that `sendmail` is hanging ?

**Comment by hwmrocker** [comment] 2016-12-07 10:30
@thijstriemstra any updates?

**Comment by hwmrocker** [comment] 2016-12-21 13:10
@thijstriemstra i will close this ticket now. If the problem continues for you please provide more information and reopen it or create a new ticket.

**Closed as completed by hwmrocker** 2016-12-21 13:10 UTC
